SELECT *
FROM PRODUCTION.GSHEETS.ARP_AUDITS
ORDER BY DATE DESC
;
CREATE OR REPLACE TEMP TABLE TEMP_TABLE AS(
SELECT A.CITY, A.DATE, A.ORDER_ID, A.RIDER_ID,
CASE WHEN A.VEHICLE IN ('Moped', 'Moped/Scooter') THEN 'SC' 
WHEN A.VEHICLE = 'Bicycle' THEN 'BI'
WHEN A.VEHICLE = 'Car' THEN 'MV'
ELSE NULL END AS VEHICLE_TYPE_REPORTED,

CASE WHEN VEHICLE_TYPE_NAME IN ('Bicycle', 'Electric Bicycle') THEN 'BI'
WHEN VEHICLE_TYPE_NAME IN ('Scooter / Motorcycle', 'Electric Motorcycle') THEN 'SC'
WHEN VEHICLE_TYPE_NAME = 'Motor Vehicle' THEN 'MV'
ELSE NULL END AS VEHICLE_TYPE_ADMIN

FROM PRODUCTION.GSHEETS.ARP_AUDITS AS A
LEFT JOIN PRODUCTION.DENORMALISED.ORDERS AS B 
ON A.ORDER_ID = B.ID AND A.RIDER_ID = B.DRIVER_ID
WHERE ORDER_ID IS NOT NULL
    AND RIDER_ID IS NOT NULL
ORDER BY DATE DESC
);

SELECT *
FROM TEMP_TABLE
ORDER BY DATE DESC
;

SELECT DATE_TRUNC('MONTH', DATE) MONTH_YEAR, COUNT(*)
FROM TEMP_TABLE
GROUP BY MONTH_YEAR
ORDER BY MONTH_YEAR
;
CREATE OR REPLACE TEMP TABLE TEMP_TABLE2 AS(
SELECT DATE_TRUNC('MONTH', DATE) MONTH_YEAR, COUNT(*) COUNT_RIDERS, VEHICLE_TYPE_REPORTED, VEHICLE_TYPE_ADMIN
FROM TEMP_TABLE
WHERE VEHICLE_TYPE_ADMIN IS NOT NULL AND VEHICLE_TYPE_REPORTED IS NOT NULL
GROUP BY MONTH_YEAR, VEHICLE_TYPE_REPORTED, VEHICLE_TYPE_ADMIN
ORDER BY MONTH_YEAR, VEHICLE_TYPE_REPORTED, VEHICLE_TYPE_ADMIN
)
;
SELECT MONTH_YEAR, 
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'SC' AND VEHICLE_TYPE_ADMIN = 'SC' THEN COUNT_RIDERS ELSE 0 END) SC_SC,
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'SC' AND VEHICLE_TYPE_ADMIN = 'BI' THEN COUNT_RIDERS ELSE 0 END) SC_BI,
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'SC' AND VEHICLE_TYPE_ADMIN = 'MV' THEN COUNT_RIDERS ELSE 0 END) SC_MV,
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'BI' AND VEHICLE_TYPE_ADMIN = 'SC' THEN COUNT_RIDERS ELSE 0 END) BI_SC,
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'BI' AND VEHICLE_TYPE_ADMIN = 'BI' THEN COUNT_RIDERS ELSE 0 END) BI_BI,
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'BI' AND VEHICLE_TYPE_ADMIN = 'MV' THEN COUNT_RIDERS ELSE 0 END) BI_MV,
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'MV' AND VEHICLE_TYPE_ADMIN = 'SC' THEN COUNT_RIDERS ELSE 0 END) MV_SC,
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'MV' AND VEHICLE_TYPE_ADMIN = 'BI' THEN COUNT_RIDERS ELSE 0 END) MV_BI,
SUM(CASE WHEN VEHICLE_TYPE_REPORTED = 'MV' AND VEHICLE_TYPE_ADMIN = 'MV' THEN COUNT_RIDERS ELSE 0 END) MV_MV

FROM TEMP_TABLE2
GROUP BY MONTH_YEAR
ORDER BY MONTH_YEAR
