

WITH HOURS AS(
SELECT 
  DRIVER_ID, CITY_NAME,  DATE,
    CASE 
		WHEN DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 1  THEN 'Mon Lunch'
		WHEN DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 3  THEN 'Wed Dinner'
		WHEN DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 5  THEN 'Fri Dinner'
	END AS PEAK,
  CASE 
		WHEN DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 1  THEN SUM(HRS_WORKED_PEAK_LUNCH) 
		WHEN DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 3  THEN SUM(HRS_WORKED_PEAK_DINNER)
		WHEN DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 5  THEN SUM(HRS_WORKED_PEAK_DINNER)
	END AS PEAK_HOURS,
	SUM(HOURS_WORKED_ADJUSTED) AS ALL_HOURS
  
FROM PRODUCTION.DENORMALISED.DRIVER_HOURS_WORKED

WHERE CITY_NAME IN 
	('Bath', 'Chelmsford', 'Cambridge', 'Southampton', 'Royal Tunbridge Wells', 'Colchester', 'Brighton', 'Bournemouth', 'Exeter', 'Cheltenham', 'Oxford', 'Plymouth', 'Harrogate', 'Newbury', 'Hereford', 'Haywards Heath', 'Durham', 'Bury St Edmunds', 'Rushden', 'Eastbourne', 'Reigate', 'Chichester', 'Margate', 'Hastings', 'Deal', 'Sevenoaks', 'Aberystwyth', 'Cirencester', 'Dorchester', 'St Andrews', 'Ely', 'Falmouth', 'Haslemere', 'Truro', 'Stratford upon Avon', 'Saint Austell')
	AND	(DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 1 OR DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 3 OR DAYOFWEEK(ADJUSTED_CLOCK_IN_LOCAL) = 5)
	AND DATE BETWEEN '2024-05-27' AND '2024-06-29'
GROUP BY 
  DRIVER_ID, CITY_NAME, DATE, ADJUSTED_CLOCK_IN_LOCAL
ORDER BY 
  CITY_NAME, DRIVER_ID, DATE
),


ORDERS AS(
SELECT 
  DRIVER_ID, CITY_NAME, COUNT(STATUS) ORDER_COUNT, DATE(LOCAL_TIME_OA_CREATED_AT) AS DATE,
  CASE 
    WHEN DAYOFWEEK(LOCAL_TIME_OA_CREATED_AT) = 1 AND EXTRACT(HOUR FROM LOCAL_TIME_OA_CREATED_AT) BETWEEN 12 AND 14 THEN 'Mon Lunch'
    WHEN DAYOFWEEK(LOCAL_TIME_OA_CREATED_AT) = 3 AND EXTRACT(HOUR FROM LOCAL_TIME_OA_CREATED_AT) BETWEEN 18 AND 21 THEN 'Wed Dinner'
    WHEN DAYOFWEEK(LOCAL_TIME_OA_CREATED_AT) = 5 AND EXTRACT(HOUR FROM LOCAL_TIME_OA_CREATED_AT) BETWEEN 18 AND 21 THEN 'Fri Dinner' ELSE NULL
END AS Period

FROM PRODUCTION.denormalised.orders 

WHERE
  COUNTRY_NAME IN ('UK', 'Ireland')
  AND CITY_NAME IN ('Bath', 'Chelmsford', 'Cambridge', 'Southampton', 'Royal Tunbridge Wells', 'Colchester', 'Brighton', 'Bournemouth', 'Exeter', 'Cheltenham', 'Oxford', 'Plymouth', 'Harrogate', 'Newbury', 'Hereford', 'Haywards Heath', 'Durham', 'Bury St Edmunds', 'Rushden', 'Eastbourne', 'Reigate', 'Chichester', 'Margate', 'Hastings', 'Deal', 'Sevenoaks', 'Aberystwyth', 'Cirencester', 'Dorchester', 'St Andrews', 'Ely', 'Falmouth', 'Haslemere', 'Truro', 'Stratford upon Avon', 'Saint Austell')
  AND STATUS = 'DELIVERED'  
AND (
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-05-27 12:00') AND TO_TIMESTAMP('2024-05-27 14:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-05-29 18:00') AND TO_TIMESTAMP('2024-05-29 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-05-31 18:00') AND TO_TIMESTAMP('2024-05-31 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-03 12:00') AND TO_TIMESTAMP('2024-06-03 14:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-05 18:00') AND TO_TIMESTAMP('2024-06-05 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-07 18:00') AND TO_TIMESTAMP('2024-06-07 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-10 12:00') AND TO_TIMESTAMP('2024-06-10 14:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-12 18:00') AND TO_TIMESTAMP('2024-06-12 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-14 18:00') AND TO_TIMESTAMP('2024-06-14 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-17 12:00') AND TO_TIMESTAMP('2024-06-17 14:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-19 18:00') AND TO_TIMESTAMP('2024-06-19 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-21 18:00') AND TO_TIMESTAMP('2024-06-21 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-24 12:00') AND TO_TIMESTAMP('2024-06-24 14:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-26 18:00') AND TO_TIMESTAMP('2024-06-26 21:00')) OR
    (LOCAL_TIME_OA_CREATED_AT BETWEEN TO_TIMESTAMP('2024-06-28 18:00') AND TO_TIMESTAMP('2024-06-28 21:00')
    ))

  AND DRIVER_ID IS NOT NULL
GROUP BY 
  DRIVER_ID, CITY_NAME, PERIOD, DATE    
ORDER BY 
  CITY_NAME, ORDER_COUNT DESC, DRIVER_ID
)

SELECT H.DRIVER_ID, H.CITY_NAME, H.DATE, PEAK, SUM(PEAK_HOURS) PEAK_HOURS,/*  SUM(ALL_HOURS) ALL_HOURS,*/ ORDER_COUNT
FROM HOURS AS H
LEFT JOIN ORDERS AS O ON H.DRIVER_ID = O.DRIVER_ID AND H.CITY_NAME = O.CITY_NAME AND H.DATE = O.DATE
WHERE PEAK_HOURS IS NOT NULL
GROUP BY 
  H.DRIVER_ID, H.CITY_NAME, H.DATE, PEAK, ORDER_COUNT
ORDER BY 
  H.CITY_NAME, H.DRIVER_ID, H.DATE


;
