-- Reactivation Union Onboards Analysis Daily 

-- Define start date variable for ONBOARDING CTE
SET start_date = TO_DATE('2025-02-07');

-- Define CTE for Onboarding data
CREATE OR REPLACE TEMPORARY TABLE Reactivations_Onboards AS(
WITH ONBOARDING AS (
    SELECT
        LS.COUNTRY_NAME,
        LS.onboarding_area,
        LS.CITY,
        LS.RIDER_DRN,
        SUBSTR(LS.RIDER_DRN, 18) AS UUID,
        dad.driver_id,
        TO_DATE(CASE WHEN LS.LIFECYCLE_MAIN_STAGE = 'application' AND LS.STAGE_STATUS ILIKE '%completed%' THEN GREATEST(LS.EVENT_UPDATED_AT, LS.EVENT_CREATED_AT) END) AS onboarding_at_date, -- Use TO_DATE directly
        TO_DATE(LS.CREATED_IN_RIDER_ADMIN_AT) AS created_in_rider_admin_at_date, -- Use TO_DATE directly
        dad.rider_admin_status_note,
        dad.CUR_ADMIN_STATUS,
        LS.VEHICLE_TYPE
    FROM "RIDERS"."RIDER_LIFECYCLE_LATEST_STATUS" AS LS 
    LEFT JOIN "RIDERS"."RIDER_LIFECYCLE_LATEST_ONBOARDING_PHASE" AS OP -- for is returner
        ON (CASE WHEN 'yes' = 'yes' THEN LS.RIDER_DRN ELSE MD5(LS.RIDER_DRN) END) = (CASE WHEN 'yes' = 'yes' THEN OP.RIDER_DRN ELSE MD5(OP.RIDER_DRN) END)
        AND LS.LIFECYCLE_MAIN_STAGE = OP.LIFECYCLE_STAGE
    LEFT JOIN production.denormalised.driver_accounting_daily AS dad ON dad.driver_uuid = SUBSTR(LS.RIDER_DRN, 18)
    WHERE -- onboarded after start date but have had at least 5 weeks to activate, not subs or returner 
        onboarding_at_date >= $start_date -- Filter using the variable
        AND created_in_rider_admin_at_date >= $start_date -- Filter using the variable
        AND LS.ONBOARDING_PLATFORM = 'salesforce'
        AND LS.COUNTRY_NAME IN ('Ireland', 'UK')
        AND onboarding_at_date < DATEADD(DAY, -49, CURRENT_DATE)
        AND created_in_rider_admin_at_date < DATEADD(DAY, -49, CURRENT_DATE)
        AND dad.DATE >= TO_DATE(DATEADD('day', -1, DATE_TRUNC('day', CONVERT_TIMEZONE('UTC', 'Europe/London', CURRENT_TIMESTAMP()))))
        AND dad.DATE < TO_DATE(DATEADD('day', 1, DATEADD('day', -1, DATE_TRUNC('day', CONVERT_TIMEZONE('UTC', 'Europe/London', CURRENT_TIMESTAMP())))))
        AND is_substitute_account_on_admin = false
        AND OP.is_returner = false

    GROUP BY
        created_in_rider_admin_at_date, -- Group by DATE type
        onboarding_at_date, -- Group by DATE type
        LS.COUNTRY_NAME,
        LS.onboarding_area,
        LS.CITY,
        LS.rider_drn,
        UUID,
        dad.rider_admin_status_note,
        dad.CUR_ADMIN_STATUS,
        dad.driver_id,
        LS.VEHICLE_TYPE
),
LAST_WORK_DATE AS (
    SELECT A.DRIVER_ID, MAX(B.DATE) AS last_work_date, TO_DATE(A.DATE) AS CAMPAIGN_DATE
FROM PRODUCTION.GSHEETS.Reactivation_Campaign_Groups AS A
LEFT JOIN production.denormalised.driver_accounting_daily AS B ON A.DRIVER_ID = B.driver_id
WHERE B.DATE < DATEADD(day, -7, A.DATE)
    AND orders_delivered IS NOT NULL
GROUP BY A.DRIVER_ID, A.DATE
)

-- Start of the combined UNION ALL query
-- Part 1: Reactivation Data (Derived from the original DAILY_ANALYSIS logic)
SELECT
  'Reactivation' AS Source,
  B.COUNTRY_NAME,
  A.DRIVER_ID,
  TO_DATE(A.DATE) AS START_DATE,
  A.Group_Fixed,
  A.City AS City, -- Consistent naming
  A.Last_4W,
  TO_DATE(A.DATE) - C.last_work_date AS days_since_last_work,
  A.X_Value,
  A.Y_Value,
  CASE WHEN B.VEHICLE_TYPE_NAME = 'Scooter / Motorcycle' THEN 'SC'
       WHEN B.VEHICLE_TYPE_NAME = 'Electric Motorcycle' THEN 'SC'
       WHEN B.VEHICLE_TYPE_NAME = 'eScooter' THEN 'SC'
       WHEN B.VEHICLE_TYPE_NAME = 'Motor Vehicle' THEN 'MV'
       WHEN B.VEHICLE_TYPE_NAME = 'Electric Bicycle' THEN 'EB'
       WHEN B.VEHICLE_TYPE_NAME = 'Bicycle' THEN 'BI'
       ELSE 'BI'
       END AS VEHICLE_TYPE,
DATEDIFF(day, TO_DATE(A.DATE), CURRENT_DATE) AS Days_Since_Start,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) BETWEEN DATEADD(DAY, -196, TO_DATE(A.DATE)) AND DATEADD(DAY, 49, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS ORDER_COUNT,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) BETWEEN DATEADD(day, -70, TO_DATE(A.DATE)) AND DATEADD(day, -1, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_XP_Orders,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) BETWEEN DATEADD(day, 0, TO_DATE(A.DATE)) AND DATEADD(day, 14, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_Orders,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) BETWEEN DATEADD(day, 15, TO_DATE(A.DATE)) AND DATEADD(day, 49, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_XP_Orders,
-- Pre Period: Day -70 to Day -1
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -70, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D70,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -69, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D69,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -68, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D68,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -67, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D67,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -66, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D66,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -65, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D65,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -64, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D64,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -63, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D63,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -62, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D62,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -61, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D61,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -60, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D60,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -59, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D59,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -58, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D58,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -57, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D57,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -56, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D56,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -55, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D55,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -54, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D54,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -53, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D53,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -52, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D52,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -51, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D51,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -50, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D50,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -49, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D49,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -48, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D48,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -47, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D47,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -46, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D46,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -45, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D45,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -44, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D44,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -43, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D43,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -42, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D42,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -41, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D41,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -40, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D40,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -39, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D39,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -38, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D38,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -37, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D37,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -36, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D36,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -35, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D35,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -34, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D34,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -33, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D33,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -32, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D32,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -31, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D31,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -30, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D30,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -29, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D29,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -28, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D28,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -27, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D27,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -26, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D26,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -25, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D25,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -24, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D24,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -23, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D23,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -22, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D22,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -21, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D21,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -20, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D20,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -19, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D19,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -18, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D18,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -17, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D17,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -16, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D16,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -15, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D15,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -14, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D14,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -13, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D13,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -12, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D12,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -11, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D11,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -10, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D10,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -9, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D9,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -8, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D8,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -7, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D7,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -6, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D6,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -5, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D5,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -4, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D4,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -3, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D3,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -2, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D2,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, -1, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Pre_D1,
-- Experiment Period (XP): Day 0 to Day 14
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 0, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D0,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 1, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D1,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 2, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D2,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 3, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D3,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 4, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D4,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 5, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D5,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 6, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D6,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 7, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D7,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 8, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D8,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 9, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D9,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 10, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D10,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 11, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D11,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 12, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D12,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 13, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D13,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 14, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS XP_D14,
-- Post Period: Day 15 to Day 71
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 15, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D15,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 16, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D16,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 17, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D17,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 18, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D18,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 19, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D19,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 20, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D20,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 21, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D21,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 22, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D22,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 23, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D23,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 24, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D24,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 25, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D25,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 26, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D26,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 27, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D27,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 28, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D28,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 29, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D29,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 30, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D30,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 31, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D31,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 32, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D32,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 33, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D33,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 34, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D34,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 35, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D35,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 36, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D36,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 37, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D37,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 38, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D38,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 39, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D39,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 40, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D40,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 41, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D41,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 42, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D42,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 43, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D43,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 44, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D44,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 45, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D45,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 46, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D46,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 47, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D47,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 48, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D48,
  SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(day, 49, TO_DATE(A.DATE)) THEN 1 ELSE 0 END) AS Post_D49  

FROM PRODUCTION.GSHEETS.Reactivation_Campaign_Groups AS A
LEFT JOIN production.denormalised.denormalised_assignment AS B
    ON A.DRIVER_ID = B.DRIVER_ID
    AND B.COUNTRY_NAME IN ('UK', 'Ireland') -- Filter country in join
    AND TO_DATE(B.LOCAL_TIME_OA_CREATED_AT) BETWEEN DATEADD(DAY, -196, TO_DATE(A.DATE)) AND DATEADD(DAY, 49, TO_DATE(A.DATE)) -- Filter date range in join
    AND B.OA_STATUS = 'DELIVERED' -- Filter status in join
LEFT JOIN LAST_WORK_DATE AS C ON A.DRIVER_ID = C.DRIVER_ID AND TO_DATE(A.DATE) = C.CAMPAIGN_DATE
WHERE
  A.DRIVER_ID IS NOT NULL
  AND A.Occurance = 1
  AND A.Group_Fixed IN ('A', 'B')
  AND B.CITY_NAME = A.City -- Ensure the city worked matches the city targeted for the campaign week
GROUP BY
  B.COUNTRY_NAME, -- Group by country from assignment table
  A.DRIVER_ID,
  START_DATE, -- Use alias
  A.Group_Fixed,
  City,       -- Use alias
  A.Last_4W,
  C.last_work_date,
  A.X_Value,
  A.Y_Value,
  VEHICLE_TYPE
HAVING (A.Group_Fixed = 'B' OR MAX(CASE WHEN A.Group_Fixed = 'A' AND A.DRIVER_ID IN
    (SELECT driver_id
        FROM braze.rider_engagement
        WHERE sent_at >= CONVERT_TIMEZONE('Europe/London', 'UTC', CAST(TO_TIMESTAMP(TO_DATE(A.DATE)) AS TIMESTAMP_NTZ))
        AND sent_at < CONVERT_TIMEZONE('Europe/London', 'UTC', CAST(DATEADD('day', 1, TO_TIMESTAMP(TO_DATE(A.DATE))) AS TIMESTAMP_NTZ))
        AND campaign_canvas_name = 'rid-multi-reac-rec-gen-global-all-all-week45-20241106-reactivationautomation'
        AND canvas_step_name = 'Email_1_Awareness'
        ) THEN 1 ELSE 0 END) = 1) -- Keep the filter for Reactivation group A based on comms


UNION ALL

-- Part 2: Onboarding Data (Selected from the ONBOARDING CTE)--------------------------------
SELECT
    'Onboarding' AS Source,
    A.COUNTRY_NAME,
    A.driver_id AS DRIVER_ID, -- Alias to match
    A.onboarding_at_date AS START_DATE, -- Alias to match
    NULL AS Group_Fixed, -- Placeholder
    A.CITY AS City, -- Alias to match
    NULL AS Last_4W, -- Placeholder
    NULL AS days_since_last_work, 
    NULL AS X_Value, -- Placeholder
    NULL AS Y_Value, -- Placeholder
    A.VEHICLE_TYPE,
    DATEDIFF(day, A.onboarding_at_date, CURRENT_DATE) AS Days_Since_Start,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' THEN 1 ELSE 0 END) AS ORDER_COUNT,
    0 AS Pre_XP_Orders,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) BETWEEN A.onboarding_at_date AND DATEADD(day, 14, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_Orders,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) BETWEEN DATEADD(day, 15, A.onboarding_at_date) AND DATEADD(day, 49, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_XP_Orders,
-- Placeholders for Pre_D columns (assuming 0 is appropriate)
    0 AS Pre_D70, 0 AS Pre_D69, 0 AS Pre_D68, 0 AS Pre_D67, 0 AS Pre_D66, 0 AS Pre_D65, 0 AS Pre_D64,
    0 AS Pre_D63, 0 AS Pre_D62, 0 AS Pre_D61, 0 AS Pre_D60, 0 AS Pre_D59, 0 AS Pre_D58, 0 AS Pre_D57,
    0 AS Pre_D56, 0 AS Pre_D55, 0 AS Pre_D54, 0 AS Pre_D53, 0 AS Pre_D52, 0 AS Pre_D51, 0 AS Pre_D50,
    0 AS Pre_D49, 0 AS Pre_D48, 0 AS Pre_D47, 0 AS Pre_D46, 0 AS Pre_D45, 0 AS Pre_D44, 0 AS Pre_D43,
    0 AS Pre_D42, 0 AS Pre_D41, 0 AS Pre_D40, 0 AS Pre_D39, 0 AS Pre_D38, 0 AS Pre_D37, 0 AS Pre_D36,
    0 AS Pre_D35, 0 AS Pre_D34, 0 AS Pre_D33, 0 AS Pre_D32, 0 AS Pre_D31, 0 AS Pre_D30, 0 AS Pre_D29,
    0 AS Pre_D28, 0 AS Pre_D27, 0 AS Pre_D26, 0 AS Pre_D25, 0 AS Pre_D24, 0 AS Pre_D23, 0 AS Pre_D22,
    0 AS Pre_D21, 0 AS Pre_D20, 0 AS Pre_D19, 0 AS Pre_D18, 0 AS Pre_D17, 0 AS Pre_D16, 0 AS Pre_D15,
    0 AS Pre_D14, 0 AS Pre_D13, 0 AS Pre_D12, 0 AS Pre_D11, 0 AS Pre_D10, 0 AS Pre_D9,  0 AS Pre_D8,
    0 AS Pre_D7,  0 AS Pre_D6,  0 AS Pre_D5,  0 AS Pre_D4,  0 AS Pre_D3,  0 AS Pre_D2,  0 AS Pre_D1,
-- Experiment Period (XP): Day 0 to Day 14 relative to onboarding_at_date
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = A.onboarding_at_date THEN 1 ELSE 0 END) AS XP_D0, -- simplified condition
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 1, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D1,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 2, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D2,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 3, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D3,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 4, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D4,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 5, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D5,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 6, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D6,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 7, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D7,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 8, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D8,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 9, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D9,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 10, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D10,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 11, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D11,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 12, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D12,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 13, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D13,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 14, A.onboarding_at_date) THEN 1 ELSE 0 END) AS XP_D14,
-- Post Period: Day 15 to Day 71 relative to onboarding_at_date
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 15, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D15,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 16, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D16,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 17, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D17,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 18, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D18,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 19, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D19,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 20, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D20,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 21, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D21,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 22, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D22,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 23, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D23,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 24, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D24,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 25, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D25,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 26, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D26,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 27, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D27,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 28, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D28,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 29, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D29,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 30, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D30,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 31, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D31,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 32, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D32,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 33, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D33,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 34, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D34,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 35, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D35,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 36, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D36,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 37, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D37,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 38, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D38,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 39, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D39,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 40, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D40,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 41, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D41,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 42, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D42,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 43, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D43,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 44, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D44,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 45, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D45,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 46, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D46,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 47, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D47,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 48, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D48,
    SUM(CASE WHEN OA_STATUS = 'DELIVERED' AND TO_DATE(LOCAL_TIME_OA_CREATED_AT) = DATEADD(DAY, 49, A.onboarding_at_date) THEN 1 ELSE 0 END) AS Post_D49

FROM ONBOARDING AS A
LEFT JOIN production.denormalised.denormalised_assignment AS B 
    ON A.DRIVER_ID = B.DRIVER_ID
    AND B.COUNTRY_NAME IN ('UK', 'Ireland') -- Moved from WHERE
    AND TO_DATE(B.LOCAL_TIME_OA_CREATED_AT) >= A.onboarding_at_date -- Moved from WHERE and filter assignments on or after onboarding date
    AND B.OA_STATUS = 'DELIVERED' -- Moved from WHERE and consider only delivered assignments for summing
GROUP BY
    A.COUNTRY_NAME,
    A.DRIVER_ID, -- Use alias
    START_DATE, -- Use alias
    City, -- Use alias
    A.CUR_ADMIN_STATUS,
    A.VEHICLE_TYPE

-- Optional: Add ORDER BY clause here to sort the final combined result set
-- ORDER BY START_DATE, DRIVER_ID

)
;


-- sample SELECT * FROM Reactivations_Onboards limit 100;
