-- ZONE TO AA WITH OV
SELECT
    CD.ZONE_CODE,
    CD.ZONE_NAME,
    CD.CITY_DETAILED,
    ZA.CITY_NAME,
    DZMH.cluster_name,
    AFM.ARCHETYPE,
    ZA.MAIN_ADMINISTRATIVE_AREA,
    ZA.ADMINISTRATIVE_AREA_1,
    ZA.ADMINISTRATIVE_AREA_2,
    ZA.ADMINISTRATIVE_AREA_3,
    ZA.ADMINISTRATIVE_AREA_4,
    ZA.POSTAL_TOWN,
    ZA.COUNTRY_NAME,
    COALESCE(SUM(orders_delivered), 0) AS orders_delivered
FROM production.reference.city_detailed AS CD
LEFT JOIN PRODUCTION.REFERENCE.ACQ__ZONES_TO_ADMIN_AREAS AS ZA
    ON CD.zone_code = ZA.zone_code
LEFT JOIN production.AGGREGATE.AGG_ZONE_DELIVERY_METRICS_HOURLY AS DZMH
    ON ZA.zone_code = DZMH.zone_code
LEFT JOIN PRODUCTION.REFERENCE.ZONES_ARCHETYPES_FOR_MARKETS AFM
    ON CD.ZONE_CODE = AFM.ZONE_CODE
WHERE
    ZA.COUNTRY_NAME IN ('UK', 'Ireland')
    AND ZA.zone_code <> 'LNTG'
    AND CD.CITY_DETAILED IS NOT NULL
    AND START_OF_PERIOD_LOCAL >= DATE_TRUNC('month', CONVERT_TIMEZONE('UTC', 'Europe/London', CURRENT_TIMESTAMP()))
    AND START_OF_PERIOD_LOCAL < DATEADD('month', 1, DATE_TRUNC('month', CONVERT_TIMEZONE('UTC', 'Europe/London', CURRENT_TIMESTAMP())))
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
ORDER BY
    ZA.CITY_NAME, 
    CD.CITY_DETAILED,
    orders_delivered DESC,
    CD.ZONE_CODE,
    ZA.MAIN_ADMINISTRATIVE_AREA


;